'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Search, Plus, MapPin, ArrowUpLeft, Route, CheckCheck, Building2, Star, SlidersHorizontal, X, Phone, Navigation, CalendarDays, ChevronUp, ChevronDown, RefreshCw, Download, Pencil, Sparkles, ListFilter, Check, CircleAlert, FileText } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { type Center, statuses, today, fa, dateLabel, matches, distance, mapLink, normalize } from '@/lib/centers';

type Patch={id:string;changes:Partial<Center>};
function Choice({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(v:string)=>void}){return <Select dir="rtl" value={value||'all'} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper" dir="rtl">{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function telephone(v:string){const normalized=v.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c)));const n=(normalized.match(/\+?\d{6,15}/)||[''])[0];return /^9\d{9}$|^51\d{8}$/.test(n)?'0'+n:n}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><input type="date" aria-label={label} dir="ltr" value={value} onInput={e=>onChange(e.currentTarget.value)} onChange={e=>onChange(e.target.value)}/>{value&&<small>{dateLabel(value)}</small>}</label>}

export default function Dashboard(){
 const [centers,setCenters]=useState<Center[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[saving,setSaving]=useState(false);
 const [query,setQuery]=useState(''),[scope,setScope]=useState('all'),[street,setStreet]=useState('all'),[type,setType]=useState('all'),[stage,setStage]=useState('all'),[sort,setSort]=useState('street'),[view,setView]=useState('cards'),[limit,setLimit]=useState(24);
 const [planDate,setPlanDate]=useState(today()),[anchorId,setAnchorId]=useState(''),[selectedId,setSelectedId]=useState('');
 const [form,setForm]=useState<Center|null|undefined>(undefined),[draft,setDraft]=useState<Record<string,string>>({}),[formError,setFormError]=useState('');
 const [notes,setNotes]=useState(''),[followup,setFollowup]=useState(''),[interest,setInterest]=useState('all'),[level,setLevel]=useState('all');
 const savingRef=useRef(false),centersRef=useRef(centers),selectedRef=useRef(selectedId);
 centersRef.current=centers;selectedRef.current=selectedId;
 const todayKey=today();
 const load=useCallback(async()=>{setLoading(true);setLoadError('');try{const res=await fetch('/api/centers',{cache:'no-store'});const data=await res.json() as {error?:string;centers:Center[]};if(!res.ok)throw new Error(data.error);setCenters(data.centers)}catch(e){setLoadError(e instanceof Error?e.message:'دریافت اطلاعات ممکن نشد.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const patch=useCallback(async(patches:Patch[],message?:string)=>{
  if(savingRef.current)throw new Error('صبر کنید تا ذخیره قبلی تمام شود.');savingRef.current=true;setSaving(true);
  try{const r=await fetch('/api/centers',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({patches})});const data=await r.json() as {error?:string;centers:Center[];center:Center};if(!r.ok)throw new Error(data.error);setCenters(old=>old.map(c=>data.centers.find((u:Center)=>u.id===c.id)||c));if(message)toast.success(message);return data.centers as Center[]}
  catch(e){toast.error(e instanceof Error?e.message:'ذخیره انجام نشد.');throw e}finally{savingRef.current=false;setSaving(false)}
 },[]);
 const act=(patches:Patch[],message?:string)=>{void patch(patches,message).catch(()=>{})};
 const selected=centers.find(c=>c.id===selectedId),anchor=centers.find(c=>c.id===anchorId);
 const plan=useMemo(()=>centers.filter(c=>c.planDate===planDate).sort((a,b)=>a.planOrder-b.planOrder||a.name.localeCompare(b.name,'fa')),[centers,planDate]);
 const completed=centers.filter(c=>c.visited).length;
 const due=centers.filter(c=>c.followupDate&&c.followupDate<=todayKey&&c.status!=='signed'&&c.status!=='paused');
 const streetStats=useMemo(()=>{const m=new Map<string,Center[]>();centers.forEach(c=>{const key=c.street||'خیابان ثبت نشده';m.set(key,[...(m.get(key)||[]),c])});return [...m].map(([name,items])=>({name,items,done:items.filter(c=>c.visited).length,remaining:items.filter(c=>!c.visited&&c.status!=='paused').length})).sort((a,b)=>b.remaining-a.remaining||a.name.localeCompare(b.name,'fa'))},[centers]);
 const bestStreet=streetStats.find(s=>!s.name.includes('تأیید')&&!s.name.includes('نشده')&&s.remaining>0);
 const filtered=useMemo(()=>{
  const rows=centers.filter(c=>matches(c,query)&&(street==='all'||c.street===street)&&(type==='all'||c.type===type)&&(stage==='all'||c.status===stage)&&(scope==='all'||scope==='new'&&!c.visited||scope==='visited'&&c.visited||scope==='favorites'&&c.favorite||scope==='due'&&!!c.followupDate&&c.followupDate<=todayKey&&c.status!=='signed'&&c.status!=='paused'));
  return rows.sort((a,b)=>{if(sort==='near'&&anchor)return distance(anchor,a)-distance(anchor,b)||a.name.localeCompare(b.name,'fa');if(sort==='name')return a.name.localeCompare(b.name,'fa');if(sort==='followup')return (a.followupDate||'9999').localeCompare(b.followupDate||'9999')||a.name.localeCompare(b.name,'fa');return a.street.localeCompare(b.street,'fa')||a.name.localeCompare(b.name,'fa')})
 },[centers,query,street,type,stage,scope,sort,anchor,todayKey]);
 useEffect(()=>{setLimit(24)},[query,scope,street,type,stage,sort,view]);
 const openDetail=(c:Center)=>{setSelectedId(c.id);setNotes(c.notes||'');setFollowup(c.followupDate||'');setInterest(c.interest||'all');setLevel(c.level||'all')};
 const addPlan=(c:Center)=>{act([{id:c.id,changes:{planDate,planOrder:plan.length?Math.max(...plan.map(x=>x.planOrder))+1:0}}],'به برنامه بازدید اضافه شد.')};
 const toggleVisit=(c:Center,v:boolean)=>act([{id:c.id,changes:{visited:v,status:v&&c.status==='new'?'first':!v?'new':c.status}}],v?'مراجعه ثبت شد.':'وضعیت به مراجعه‌نشده برگشت.');
 const setAnchor=(c:Center)=>{setAnchorId(c.id);setSort(c.lat!=null&&c.lng!=null?'near':'street');setStreet(c.lat!=null&&c.lng!=null?'all':c.street||'all');setView('cards');toast.success(c.lat!=null&&c.lng!=null?'نقطه شروع انتخاب شد؛ مراکز نزدیک‌تر اول نمایش داده می‌شوند.':'مختصات این مرکز موجود نیست؛ مراکز همین خیابان نمایش داده می‌شوند.')};
 const move=(index:number,delta:number)=>{const arr=[...plan];if(index+delta<0||index+delta>=arr.length)return;[arr[index],arr[index+delta]]=[arr[index+delta],arr[index]];act(arr.map((c,i)=>({id:c.id,changes:{planOrder:i}})))};
 const arrange=()=>{if(plan.length<2)return;const start=plan.find(c=>c.id===anchorId)||plan[0];const left=plan.filter(c=>c.id!==start.id),ordered=[start];while(left.length){const last=ordered[ordered.length-1];left.sort((a,b)=>{const da=distance(last,a),db=distance(last,b);if(Number.isFinite(da)||Number.isFinite(db))return da-db;return Number(b.street===last.street)-Number(a.street===last.street)||a.street.localeCompare(b.street,'fa')});ordered.push(left.shift()!)}act(ordered.map((c,i)=>({id:c.id,changes:{planOrder:i}})),'ترتیب تقریبی بر اساس فاصله مستقیم و خیابان تنظیم شد.')};
 const openForm=(c:Center|null)=>{setForm(c);setFormError('');const keys=['name','type','street','neighborhood','address','phone','mobile','instagram','services','specialties','insurance','hours','doctors','mapUrl','lat','lng'];setDraft(Object.fromEntries(keys.map(k=>[k,c?(c[k as keyof Center]?.toString()||''):k==='type'?'مطب':''])))};
 const submitForm=async(e:React.FormEvent)=>{e.preventDefault();if(savingRef.current)return;setFormError('');if(!draft.name?.trim()||!draft.street?.trim()||!draft.address?.trim()){setFormError('نام مرکز، خیابان و آدرس را وارد کنید.');return}if((!!draft.lat)!==(!!draft.lng)){setFormError('عرض و طول جغرافیایی را هر دو وارد کنید یا هر دو خالی بگذارید.');return}
  const input={...draft,lat:draft.lat?Number(draft.lat):null,lng:draft.lng?Number(draft.lng):null};
  if(form){try{await patch([{id:form.id,changes:input}],'اطلاعات مرکز به‌روز شد.');setForm(undefined)}catch{setFormError('ذخیره انجام نشد؛ اطلاعات شما در فرم باقی مانده است.')}return}
  savingRef.current=true;setSaving(true);try{const r=await fetch('/api/centers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const data=await r.json() as {error?:string;centers:Center[];center:Center};if(!r.ok)throw new Error(data.error);setCenters(old=>[...old,data.center]);setForm(undefined);toast.success('مرکز جدید ثبت شد.');openDetail(data.center)}catch(e){setFormError(e instanceof Error?e.message:'ثبت مرکز انجام نشد.')}finally{savingRef.current=false;setSaving(false)}
 };
 const exportCsv=()=>{const header=['نام مرکز','خیابان','محله','آدرس','موبایل','تلفن','خدمات','بیمه','ساعت فعالیت','مراجعه','مرحله','پیگیری بعدی','برنامه بازدید','توضیحات'];const safe=(v:unknown)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const rows=filtered.map(c=>[c.name,c.street,c.neighborhood,c.address,c.mobile,c.phone,c.services,c.insurance,c.hours,c.visited?'انجام شد':'نشده',statuses[c.status],c.followupDate,c.planDate,c.notes]);const url=URL.createObjectURL(new Blob(['\uFEFF'+[header,...rows].map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ava-centers-'+todayKey+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const reset=()=>{setQuery('');setStreet('all');setType('all');setStage('all');setScope('all')};
 const mapPlan=()=>{const valid=plan.filter(c=>c.lat!=null&&c.lng!=null).slice(0,9);if(valid.length<2)return null;return `https://www.google.com/maps/dir/?api=1&origin=${valid[0].lat},${valid[0].lng}&destination=${valid[valid.length-1].lat},${valid[valid.length-1].lng}&waypoints=${valid.slice(1,-1).map(c=>c.lat+','+c.lng).join('|')}&travelmode=driving`};
 const formFields:[string,string,string?][]=[['name','نام مرکز *'],['type','نوع مرکز'],['street','خیابان اصلی *'],['neighborhood','محله'],['address','آدرس دقیق *','textarea'],['mobile','موبایل مسئول'],['phone','تلفن مرکز'],['instagram','اینستاگرام یا سایت'],['services','خدمات اصلی','textarea'],['specialties','خدمات تخصصی'],['doctors','پزشکان و تخصص‌ها','textarea'],['insurance','بیمه‌های طرف قرارداد'],['hours','روز و ساعت دقیق فعالیت'],['mapUrl','لینک نقشه'],['lat','عرض جغرافیایی (اختیاری)'],['lng','طول جغرافیایی (اختیاری)']];
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(t:unknown)=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:'search_ava_centers',title:'جست‌وجوی مراکز آوا',description:'Find centers by name, street or service. Read only.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const q=(input as {query:string}).query;if(typeof q!=='string')throw new Error('query must be a string');return centersRef.current.filter(c=>matches(c,q)).slice(0,30).map(c=>({id:c.id,name:c.name,street:c.street,visited:c.visited,status:c.status}))}});
  register({name:'set_ava_visit_status',title:'ثبت وضعیت مراجعه',description:'Save whether a center has been visited and update its visible status.',inputSchema:{type:'object',properties:{id:{type:'string'},visited:{type:'boolean'}},required:['id','visited'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const p=input as {id:string;visited:boolean};if(typeof p.id!=='string'||typeof p.visited!=='boolean')throw new Error('Invalid input');const c=centersRef.current.find(c=>c.id===p.id);if(!c)throw new Error('Center not found');await patch([{id:c.id,changes:{visited:p.visited,status:p.visited&&c.status==='new'?'first':!p.visited?'new':c.status}}]);return {id:c.id,visited:p.visited}}});return()=>lifecycle.abort()
 },[patch]);

 return <main className="workspace" dir="rtl"><Toaster dir="rtl" theme="light" position="bottom-center" richColors/><header className="topbar"><div className="brand"><span className="brandmark">آ</span><div><strong>آوا</strong><span>دفتر بازدید مشهد</span></div></div><span className="city"><MapPin size={16}/> مشهد، خراسان رضوی</span><div className="top-actions"><button className="iconbutton" aria-label="تازه‌سازی اطلاعات" title="تازه‌سازی" onClick={()=>void load()} disabled={loading||saving}><RefreshCw size={18}/></button><button className="primary" disabled={loading||!!loadError} onClick={()=>openForm(null)}><Plus size={18}/> مرکز جدید</button></div></header>
 <button className="mobile-plan-jump" onClick={()=>document.getElementById('visit-plan')?.scrollIntoView({behavior:'smooth'})}><Route size={18}/> برنامه بازدید ({fa(plan.length)})</button><div className="page"><div className="page-heading"><div><span className="eyebrow">همراه تیم جذب مراکز</span><h1>مرکز بعدی، همکاری بعدی</h1><p>جست‌وجو کنید، برنامه بچینید و نتیجه بازدید را ثبت کنید.</p></div><div className="date-badge"><CalendarDays size={18}/>{dateLabel(todayKey)}</div></div>
 <section className="stats"><div><Building2/><strong>{loading&&!centers.length?'…':fa(centers.length)}</strong><span>مرکز در فهرست</span></div><div><CheckCheck/><strong>{fa(completed)} <small>از {fa(centers.length)}</small></strong><span>بازدید انجام‌شده</span></div><div><Route/><strong>{fa(plan.length)}</strong><span>در برنامه {planDate===todayKey?'امروز':'انتخابی'}</span></div></section>
 {loadError&&<div className="error-state" role="alert"><CircleAlert/><span>{loadError}</span><button className="outline" onClick={()=>void load()}>تلاش دوباره</button></div>}
 <div className="work-grid"><section className="main-column"><div className="searchbar"><Search/><input aria-label="جست‌وجوی مراکز" placeholder="نام مرکز، خیابان، پزشک یا خدمت..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="iconbutton" aria-label="پاک کردن جست‌وجو" onClick={()=>setQuery('')}><X size={16}/></button>}</div>
 <div className="filters"><Choice label="فیلتر خیابان" value={street} onChange={setStreet} options={[["all","همه خیابان‌ها"],...streetStats.map(s=>[s.name,s.name] as [string,string]).sort((a,b)=>a[1].localeCompare(b[1],'fa'))]}/><Choice label="فیلتر نوع مرکز" value={type} onChange={setType} options={[["all","همه انواع مراکز"],...[...new Set(centers.map(c=>c.type).filter(Boolean))].sort().map(t=>[t,t] as [string,string])]}/><Choice label="مرحله همکاری" value={stage} onChange={setStage} options={[["all","همه مراحل"],...Object.entries(statuses)]}/>{(query||street!=='all'||type!=='all'||stage!=='all')&&<button className="quiet" onClick={reset}><X size={15}/> پاک کردن</button>}</div>
 <Tabs dir="rtl" value={scope} onValueChange={setScope} className="scope-tabs"><TabsList className="scope-list" variant="line"><TabsTrigger value="all">همه</TabsTrigger><TabsTrigger value="new">مراجعه نشده</TabsTrigger><TabsTrigger value="visited">مراجعه شده</TabsTrigger><TabsTrigger value="favorites"><Star size={15}/> منتخب‌ها</TabsTrigger><TabsTrigger value="due">پیگیری‌ها {due.length>0&&<b className="countbadge">{fa(due.length)}</b>}</TabsTrigger></TabsList></Tabs>
 <div className="sectionline"><div className="view-switch"><button className={view==='cards'?'active':''} onClick={()=>setView('cards')} aria-pressed={view==='cards'}>مراکز</button><button className={view==='streets'?'active':''} onClick={()=>setView('streets')} aria-pressed={view==='streets'}>نمای خیابان‌ها</button></div><div className="result-actions"><span>{fa(filtered.length)} مرکز</span><button className="iconbutton" title="خروجی فهرست فیلترشده" aria-label="دریافت خروجی اکسل" onClick={exportCsv} disabled={loading||!filtered.length}><Download size={17}/></button></div></div>
 {anchor&&<div className="anchor-banner"><Navigation size={17}/><span>شروع از <strong>{anchor.name}</strong>؛ {anchor.lat!=null?'فاصله مستقیم تقریبی':'نمای خیابان'}</span><button className="iconbutton" aria-label="حذف نقطه شروع" onClick={()=>{setAnchorId('');setSort('street')}}><X size={16}/></button></div>}
 {view==='cards'&&<div className="sortline"><ListFilter size={16}/><Choice label="مرتب‌سازی مراکز" value={sort} onChange={setSort} options={[["street","به ترتیب خیابان"],["name","به ترتیب نام"],["followup","نزدیک‌ترین موعد پیگیری"],...(anchor?.lat!=null?[["near","نزدیک‌ترین به نقطه شروع"] as [string,string]]:[])]}/><span className="saved-state" aria-live="polite">{saving?'در حال ذخیره…':loading?'در حال دریافت…':'تغییرات به‌صورت آنلاین ذخیره می‌شوند'}</span></div>}
 {loading&&!centers.length?<div className="cards">{[1,2,3,4].map(i=><Skeleton key={i} className="h-64 rounded-xl bg-slate-200"/>)}</div>:view==='streets'?<div className="street-grid">{streetStats.filter(s=>s.items.some(c=>filtered.some(f=>f.id===c.id))).map(s=><button className="street-card" key={s.name} onClick={()=>{setStreet(s.name);setView('cards')}}><div><MapPin size={20}/><span>{s.name}</span><ArrowUpLeft size={17}/></div><strong>{fa(s.remaining)} مرکز برای شروع بازدید</strong><Progress value={s.items.length?100*s.done/s.items.length:0} aria-label={`پیشرفت بازدید ${s.name}`} className="street-progress"/><p>{fa(s.done)} بازدید از {fa(s.items.length)} مرکز</p></button>)}</div>:<div className="cards">{filtered.slice(0,limit).map(c=>{const planned=c.planDate===planDate;const km=anchor?distance(anchor,c):Infinity;return <article className={'center-card '+(c.visited?'was-visited':'')} key={c.id}><div className="cardtop"><span className="type">{c.type||'مرکز'}</span><div className="card-badges"><span className={'status '+(c.visited?'done':'')}>{c.visited?'مراجعه شده':'مراجعه نشده'}</span><button className={'iconbutton star '+(c.favorite?'selected':'')} title="منتخب" aria-label={`منتخب کردن ${c.name}`} aria-pressed={c.favorite} disabled={saving} onClick={()=>act([{id:c.id,changes:{favorite:!c.favorite}}])}><Star size={18} fill={c.favorite?'currentColor':'none'}/></button></div></div><button className="name-button" onClick={()=>openDetail(c)}><h3>{c.name}</h3></button><p className="address"><MapPin size={15}/><span><strong>{c.street||'خیابان ثبت نشده'}</strong><br/>{c.address||'آدرس ثبت نشده'}</span></p><p className="services">{c.services||c.specialties||'خدمات هنوز ثبت نشده'}</p><div className="card-metadata"><span>{statuses[c.status]||'شروع نشده'}</span>{c.followupDate&&<span className={c.followupDate<=todayKey?'due-label':''}><CalendarDays size={13}/>{dateLabel(c.followupDate)}</span>}{Number.isFinite(km)&&<span>{km<.1?'همین محدوده':km.toLocaleString('fa-IR',{maximumFractionDigits:1})+' کیلومتر'}</span>}</div><div className="visit-control"><label><Checkbox className="visit-checkbox" checked={c.visited} disabled={saving} onCheckedChange={v=>toggleVisit(c,v===true)} aria-label={`ثبت مراجعه ${c.name}`}/><span>مراجعه انجام شد</span></label><a className="quiet" href={mapLink(c)} target="_blank" rel="noopener noreferrer" aria-label={`نقشه ${c.name}`}><Navigation size={15}/> نقشه</a></div><div className="cardbottom"><button className="quiet" onClick={()=>openDetail(c)}>جزئیات و یادداشت <ArrowUpLeft size={16}/></button><button className={'outline '+(planned?'in-plan':'')} disabled={saving} onClick={()=>planned?act([{id:c.id,changes:{planDate:'',planOrder:0}}]):addPlan(c)}>{planned?<Check size={16}/>:<Plus size={16}/>} {planned?'در برنامه':'برنامه بازدید'}</button></div></article>})}</div>}
 {!loading&&!loadError&&!filtered.length&&<div className="empty-results"><Search size={32}/><h3>مرکزی با این مشخصات پیدا نشد</h3><p>عبارت کوتاه‌تری جست‌وجو کنید یا فیلترها را تغییر دهید.</p><button className="outline" onClick={reset}>نمایش همه مراکز</button></div>}
 {view==='cards'&&filtered.length>limit&&<button className="loadmore outline" onClick={()=>setLimit(l=>l+24)}>نمایش مراکز بیشتر ({fa(filtered.length-limit)})</button>}
 </section><aside className="planner" id="visit-plan"><div className="planner-heading"><div><span className="eyebrow">قدم بعدی</span><h2>برنامه بازدید شما</h2></div><Route size={25}/></div><label className="plan-date-label">تاریخ برنامه<input type="date" aria-label="تاریخ برنامه بازدید" dir="ltr" value={planDate} onInput={e=>{if(e.currentTarget.value)setPlanDate(e.currentTarget.value)}} onChange={e=>{if(e.target.value)setPlanDate(e.target.value)}}/></label><p className="plan-date-persian">{dateLabel(planDate)}</p>
 {!plan.length?<div className="plan-empty"><Route size={36}/><h3>از یک خیابان شروع کنید</h3><p>روی «برنامه بازدید» هر مرکز بزنید. ترتیب را اینجا تنظیم کنید.</p></div>:<><div className="plan-progress"><span>{fa(plan.filter(c=>c.visited).length)} از {fa(plan.length)} مراجعه انجام شده</span><Progress value={100*plan.filter(c=>c.visited).length/plan.length} aria-label="پیشرفت برنامه بازدید"/></div><ol className="plan-list">{plan.map((c,i)=><li key={c.id}><span className={'stop-number '+(c.visited?'done':'')}>{c.visited?<Check size={15}/>:fa(i+1)}</span><div className="stop-body"><button className="stop-name" onClick={()=>openDetail(c)}>{c.name}</button><small>{c.street}</small><div className="stop-actions"><a href={mapLink(c)} target="_blank" rel="noopener noreferrer">مسیریابی <ArrowUpLeft size={12}/></a><button disabled={saving} onClick={()=>toggleVisit(c,!c.visited)}>{c.visited?'برگشت وضعیت':'ثبت مراجعه'}</button></div></div><div className="stop-controls"><button disabled={saving||i===0} aria-label={`بالا بردن ${c.name}`} onClick={()=>move(i,-1)}><ChevronUp size={16}/></button><button disabled={saving||i===plan.length-1} aria-label={`پایین بردن ${c.name}`} onClick={()=>move(i,1)}><ChevronDown size={16}/></button><button disabled={saving} aria-label={`حذف ${c.name} از برنامه`} onClick={()=>act([{id:c.id,changes:{planDate:'',planOrder:0}}])}><X size={13}/></button></div></li>)}</ol><button className="plan-sort" disabled={saving||plan.length<2} onClick={arrange}><Sparkles size={16}/> مرتب‌سازی تقریبی مسیر</button><p className="plan-note">از نقطه شروع انتخابی یا اولین مرکز؛ بر اساس فاصله مستقیم و خیابان، بدون محاسبه ترافیک.</p>{mapPlan()&&<a className="plan-route" href={mapPlan()!} target="_blank" rel="noopener noreferrer"><Navigation size={16}/> باز کردن مسیر در گوگل‌مپ</a>}{mapPlan()&&<p className="plan-note">حداکثر ۹ مرکز دارای مختصات؛ مراکز بدون مختصات را جدا مسیریابی کنید.</p>}</>}
 {bestStreet&&<div className="tip"><strong><Sparkles size={15}/> پیشنهاد شروع</strong><p>خیابان {bestStreet.name} با {fa(bestStreet.remaining)} مرکزِ مراجعه‌نشده.</p><button onClick={()=>{setStreet(bestStreet.name);setScope('new');setView('cards');window.scrollTo({top:240,behavior:'smooth'})}}>دیدن مراکز این خیابان <ArrowUpLeft size={14}/></button></div>}
 {due.length>0&&<button className="followup-alert" onClick={()=>{reset();setScope('due');setView('cards')}}><CalendarDays size={19}/><span>{fa(due.length)} پیگیری برای امروز یا قبل‌تر</span><ArrowUpLeft size={15}/></button>}
 </aside></div><footer className="workspace-footer">آوا · دفتر بازدید مشهد <span>اطلاعات اولیه از فهرست مراکز شما</span></footer></div>

 <Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelectedId('')}}><SheetContent side="left" className="detail-sheet" dir="rtl"><SheetHeader><SheetTitle>{selected?.name}</SheetTitle><SheetDescription>{selected?.type} · {selected?.street}</SheetDescription></SheetHeader>{selected&&<div className="detail-body"><div className="detail-actions"><a className="primary" href={mapLink(selected)} target="_blank" rel="noopener noreferrer"><Navigation size={16}/> مسیریابی</a>{(selected.mobile||selected.phone)&&<a className="outline" href={'tel:'+telephone(selected.mobile||selected.phone)}><Phone size={16}/> تماس</a>}<button className="outline" onClick={()=>openForm(selected)}><Pencil size={16}/> ویرایش</button></div><div className="detail-visit"><label><Checkbox className="visit-checkbox" checked={selected.visited} disabled={saving} onCheckedChange={v=>toggleVisit(selected,v===true)}/> مراجعه انجام شده</label>{selected.visitedAt&&<span>{dateLabel(selected.visitedAt)}</span>}</div><label className="field"><span>مرحله همکاری</span><Choice label="تغییر مرحله همکاری" value={selected.status} options={Object.entries(statuses)} onChange={v=>act([{id:selected.id,changes:{status:v,...(['first','followup','signed'].includes(v)?{visited:true}:v==='new'?{visited:false}:{})}}])}/></label><div className="detail-info">{[['آدرس دقیق',selected.address],['تلفن',selected.phone],['موبایل',selected.mobile],['اینستاگرام / سایت',selected.instagram],['روز و ساعت فعالیت',selected.hours],['خدمات اصلی',selected.services],['خدمات تخصصی',selected.specialties],['بیمه‌های طرف قرارداد',selected.insurance],['پزشکان',selected.doctors]].map(([k,v])=><div key={k}><dt>{k}</dt><dd dir={['تلفن','موبایل'].includes(k)?'ltr':undefined}>{v||'ثبت نشده'}</dd></div>)}</div>{(selected.streetNote||selected.coordinateNote)&&<p className="source-note"><CircleAlert size={15}/>{[selected.streetNote,selected.coordinateNote].filter(Boolean).join(' · ')}</p>}
 <div className="detail-section"><h3><FileText size={18}/> یادداشت و پیگیری</h3><label className="field"><span>نتیجه جلسه و توضیحات</span><textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="نام مخاطب، نکته مهم جلسه و اقدام بعدی…"/></label><div className="two-fields"><DateField label="تاریخ اقدام بعدی" value={followup} onChange={setFollowup}/><label className="field"><span>علاقه به همکاری</span><Choice label="سطح علاقه" value={interest} onChange={setInterest} options={[["all","تعیین نشده"],["high","بالا"],["medium","متوسط"],["low","پایین"]]}/></label><label className="field"><span>سطح مرکز از نظر آوا</span><Choice label="سطح مرکز" value={level} onChange={setLevel} options={[["all","تعیین نشده"],["A","سطح A"],["B","سطح B"],["C","سطح C"]]}/></label></div><button className="primary full" disabled={saving} onClick={()=>act([{id:selected.id,changes:{notes,followupDate:followup,interest:interest==='all'?'':interest,level:level==='all'?'':level}}],'یادداشت و پیگیری ذخیره شد.')}><Check size={16}/>{saving?'در حال ذخیره…':'ذخیره یادداشت و پیگیری'}</button></div>
 <div className="detail-section"><h3><Route size={18}/> برنامه بازدید</h3><button className="outline full" disabled={saving} onClick={()=>addPlan(selected)}><Plus size={16}/> افزودن به برنامه {dateLabel(planDate)}</button><button className="quiet full" onClick={()=>{setAnchor(selected);setSelectedId('')}}><Navigation size={16}/> از این مرکز شروع می‌کنم</button>{selected.planDate&&<p className="muted">در برنامه {dateLabel(selected.planDate)}</p>}</div>
 {Object.keys(selected.raw||{}).length>0&&<details className="source-details"><summary>تمام اطلاعات فایل اکسل اولیه</summary><p>ردیف {fa(selected.sourceRow||0)} · شناسه اصلی {selected.sourceId}</p>{Object.entries(selected.raw).map(([k,v])=><div key={k}><strong>{k}</strong><span>{v}</span></div>)}</details>}
 </div>}</SheetContent></Sheet>
 <Dialog open={form!==undefined} onOpenChange={v=>{if(!v&&!saving)setForm(undefined)}}><DialogContent className="center-dialog" dir="rtl"><DialogHeader><DialogTitle>{form?'ویرایش اطلاعات مرکز':'افزودن مرکز جدید'}</DialogTitle><DialogDescription>نام خیابان اصلی را جدا از آدرس بنویسید تا مرکز در گروه درست قرار بگیرد.</DialogDescription></DialogHeader><form onSubmit={submitForm} className="center-form"><div className="two-fields">{formFields.map(([key,label,kind])=><label className={'field '+(kind==='textarea'?'wide':'')} key={key}><span>{label}</span>{kind==='textarea'?<textarea required={key==='address'} rows={2} value={draft[key]||''} onChange={e=>setDraft(old=>({...old,[key]:e.target.value}))}/>:<input required={['name','street'].includes(key)} type={['lat','lng'].includes(key)?'number':'text'} step="any" dir={['lat','lng','mobile','phone','mapUrl'].includes(key)?'ltr':undefined} value={draft[key]||''} onChange={e=>setDraft(old=>({...old,[key]:e.target.value}))}/>}</label>)}</div>{!form&&centers.some(c=>normalize(c.name)===normalize(draft.name||''))&&<p className="source-note">مرکزی با این نام وجود دارد؛ برای جلوگیری از ثبت تکراری، آدرس را بررسی کنید.</p>}{formError&&<p role="alert" className="form-error">{formError}</p>}<div className="form-footer"><button type="submit" className="primary" disabled={saving}>{saving?'در حال ذخیره…':form?'ذخیره تغییرات':'ثبت مرکز جدید'}</button><button className="outline" type="button" onClick={()=>setForm(undefined)} disabled={saving}>انصراف</button></div></form></DialogContent></Dialog>
 </main>
}
